version: '3.9'
services:
  # postgresql
  database:
    image: postgres
    env_file:
      - quebot.env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: quebot
      POSTGRES_USER: ${DB_USER]
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  graphql:
    image: hasura/graphql-engine:v2.0.0
    env_file:
      - quebot.env
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    volumes:
      - ./migrations:/hasura-migrations
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${DB_USER]:${DB_PASSWORD}@database:5432/quebot
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  # pgadmin
  pgAdmin:
    image: pgadmin/pgadmin4
    env_file:
      - quebot.env
    ports:
      - "5050:80"
      - "443:443"
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

